### ISSUE TITLE
server.destroy() 

### ISSUE THREAD

**Issue by wactbprot** [TopCloud/ndata#14]
With commit 3888abb6258bc5dbe798cba0e25318ea72e44cf8 I receive
the following error on the attempt to ```destroy()``` the server:

```
 connections[i].destroy();
                   ^
TypeError: Object #<EventEmitter> has no method 'destroy'
    at process.<anonymous> (../ndata/server.js:442:20)
    at process.emit (events.js:92:17)
    at Signal.wrap.onsignal (node.js:761:46)
```

I tried to make a small example and realized, that 
```js
var ndata  = require('../index')
  , conf   = {port: 9001}
  , server = ndata.createServer(conf);

server.on("ready", function(){
  server.destroy();
})
```
throws:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at EventEmitter.self.listen (.../ndata/node_modules/ncom/index.js:125:19)
    at Object.<anonymous> (.../ndata/server.js:456:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```
but I'm sure that the port (EADDRINUSE) is unused before I start the small script. Have you got any ideas? Thank you!

**Comment by jondubois** [comment]
Is that the whole code?

```js
var ndata  = require('../index')
  , conf   = {port: 9001}
  , server = ndata.createServer(conf);

server.on("ready", function(){
  server.destroy();
})
```

How do you keep the script running long enough to trigger the 'ready' event?

Did you also create a dummy HTTP server in that script?

**Comment by wactbprot** [comment]
I had the line
```js
require("http").createServer(function(req, res) {}).listen(9002);
```
to keep it running; however, I found the problem for the EADDRINUSE on my machine; sorry for that!

What remains is the
```
TypeError: Object #<EventEmitter> has no method 'destroy'
```

What do you get if you execute the tests e.g. with 
```
~/ndata $> npm run mocha
```
Don't you receive the same error?

**Comment by jondubois** [comment]
@wactbprot Sorry for the long delay, I've been really busy with SocketCluster v2.0 and the new auth engine. I haven't been able to reproduce this issue under normal conditions. I haven't tried running the test yet. I will look into this when I get the chance. Very soon hopefully.

**Comment by wactbprot** [comment]
Got it! I operated my fork with old deps; ```npm update``` solved the issue.

**Comment by jondubois** [comment]
Cool. Thanks for keeping tabs on this issue.
Maybe it was a fix I made in the Fleximap dependency a while ago which resolved the issue.
