### ISSUE TITLE
.pop() works like remove

### ISSUE THREAD

**Issue by wactbprot** [TopCloud/ndata#15]
due to the description of .pop() I expect that after:

```js
      client.set(["a","b","c"], [1,2,3], function (err){
          client.pop(["a","b","c"], function (err){
            client.get(["a","b","c"], function (err, value){
          ...
```
```value``` to be ```[1,2]``` but I receive a undefined ```value```. Do I get something wrong?

**Comment by jondubois** [comment]
@wactbprot You're right, the value should be ```[1, 2]```.
I'll fix this ASAP,

**Comment by jondubois** [comment]
Ok, fixed, it was actually an issue with the FlexiMap dependency: https://github.com/TopCloud/fleximap
No change was required to nData.

If you
```js
npm cache clean
```
then
```js
npm install ndata
```

It should fix the issue.

**Comment by wactbprot** [comment]
perfect; after
```
npm update fleximap
```
everything works fine! 
I fixed the related tests
